export  default {

  //用户接口
  account:{
    login:'login',
    logout:'logout',
    userinfo:'usrInfo'
  },
  arguments:{
    fetch:'allArgs'
  },
  sow:{
    fetch:'sows',
    fetchSingle:'sows/',
    create:'sows',
    update:'sows/',
    del:'sows/',
    copyView:'newSowInfo',
    copy:'duplicateSow',
    editPass:'sowPassThroughs/',
    submit:'submit/sow/',
    fdRefuse:'fdRefuse/sow/',
    fdApprove:'fdApprove/sow/',
    clientRefuse:'clientRefuse/sow/',
    clientApprove:'clientApprove/sow/',
    collectPO:'collectPO/sow/',
    fetchPO:'clientPos',
    updatePO:'clientPos',
    getPositionName:'positionName',
    getPositionBudget:'positionBudget',
    getSowLevel:'sowLevel',
    createPosition:'positions',
    getSowNote:'notes',
    fetchPosition:'sows/',
    fetchSinglePosition:'positions/',
    fetchAllPosition:'positions',
    updatePositionRemark:'positionRemark/',
    clientCost:'clientCost',
    createSowPositions:'sowPositions',
  },

  //系统设置接口
  setting:{
    fetch:'allSettings',
    companys:{
      fetch:'companys',
      fetchSingle:'companys/',
      create:'companys',
      update:'companys/',
      createDetail:'companyDetails',
      updateDetail:'companyDetails/',
    },
    clients:{
      fetch:'clients',
      fetchSingle:'clients/',
      create:'clients',
      update:'clients/',
      fetchTeam:'teams',
      createTeam:'teams',
      updateTeam:'teams/',
    },
    offices:{
      fetch:'offices',
      fetchSingle:'offices/',
      create:'offices',
      update:'offices/',
      createDetail:'officeDetails',
      updateDetail:'officeDetails/',
    },
    fordFunctions:{
      fetch:'fordFunctions',
      fetchSingle:'fordFunctions/',
      create:'fordFunctions',
      disabled:'fordFunctions/',
      enabled:'fordFunctions/',
    },
    currencys:{
      fetch:'currencys',
      fetchSingle:'currencys/',
      create:'currencys',
      createDetail:'currencyDetails',
      updateDetail:'currencyDetails/',
    },
    salaryTypes:{
      fetch:'salaryTypes',
      fetchSingle:'salaryTypes/',
      create:'salaryTypes',
      updateIndex:'salaryTypes/index',
    },
    stdposs:{
      fetch:'stdposs',
      fetchSingle:'stdposs/',
      create:'stdposs',
      createDetail:'stdposDetails',
      updateDetail:'stdposDetails/',
    },
    teams:{
      fetch:'teams'
    }
  }
}